// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//
// NOTE: an `adapter()` function was tried here to make `prisma db push`/`migrate` target Turso
// directly, but `PrismaConfig`'s TypeScript type doesn't actually declare that field (breaks
// `tsc`) and it didn't change db push's target anyway (kept resolving to the local `datasource.url`
// below regardless). The live Turso schema/data were set up by hand instead (raw SQL via
// `turso db shell` + a one-off dump/load script) — see conversation/memory notes. This file only
// needs to support local `prisma generate`/`db push` against dev.db.
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
